import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import Banner from '../components/banner';
import Card from '../components/card';

import kebabStoresData from '../data/coffee-stores.json';

export async function getStaticProps(context) {
  return {
    props: {
      kebabStores: kebabStoresData,
    },
  }
}

export default function Home(props) {

  const handleOnBannerBtnClick = () => {
    console.log("Hi Banner Button!")
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Döner Restaurants</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Banner buttonText="Kebabs Nearby" handleOnClick={handleOnBannerBtnClick}/>
        <div className={styles.heroImage}>
          <Image src="/static/kebab.png" width={120} height={100} alt="kebab" className="heroImage"/>
        </div>
        {props.kebabStores.length > 0 &&
        <>
          <h2 className={styles.heading2}>Berlin Stores</h2>
          <div className={styles.cardLayout}>
          {props.kebabStores.map((kebabStore) => {
                return (
                    <Card key={kebabStore.id}
                          name={kebabStore.name}
                          imgUrl={kebabStore.imgUrl}
                          href={`/doner-restaurant/${kebabStore.id}`}
                          className={styles.card}  />
                    )})}
          </div>
        </>}
      </main>
    </div>
  )
}
