import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import Banner from '../components/banner';
import Card from '../components/card';

import { fetchKebabStores } from '../lib/kebab-stores';

export async function getStaticProps(context) {
  const kebabStores = await fetchKebabStores();
  return {
    props: {
      kebabStores,
    },
  }
}

export default function Home(props) {
  const handleOnBannerBtnClick = () => {
    console.log("Hi Banner Button!")
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Döner Restaurants</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Banner buttonText="Kebabs Nearby" handleOnClick={handleOnBannerBtnClick}/>
        <div className={styles.heroImage}>
          <Image src="/static/kebab.png" width={120} height={100} alt="kebab" className="heroImage"/>
        </div>
        {props.kebabStores.length > 0 &&
        <>
          <h2 className={styles.heading2}>Berlin Stores</h2>
          <div className={styles.cardLayout}>
          {props.kebabStores.map((kebabStore) => {
                return (
                    <Card key={kebabStore.fsq_id}
                          name={kebabStore.name}
                          imgUrl='https://media.istockphoto.com/photos/close-up-of-kebab-sandwich-picture-id851493796?k=20&m=851493796&s=612x612&w=0&h=jet3Ej7Is9w4KdnqixO4ApvvHfd8jlGGawzqI3CrsDQ='
                          href={`/doner-restaurant/${kebabStore.fsq_id}`}
                          className={styles.card}  />
                    )})}
          </div>
        </>}
      </main>
    </div>
  )
}
